apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-nest-nodejs
spec:
  selector:
    matchLabels:
      app: rest-nest-nodejs
  template:
    metadata:
      labels:
        app: rest-nest-nodejs
    spec:
      containers:
        - name: rest-nest-nodejs
          image: ghcr.io/gochronicles/benchmark-rest-frameworks/rest-nest-nodejs:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rest-nest-nodejs
spec:
  type: LoadBalancer
  selector:
    app: rest-nest-nodejs
  ports:
    - port: 80
      targetPort: 3000
