apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-fastapi-python
spec:
  selector:
    matchLabels:
      app: rest-fastapi-python
  template:
    metadata:
      labels:
        app: rest-fastapi-python
    spec:
      containers:
        - name: rest-fastapi-python
          image: ghcr.io/gochronicles/benchmark-rest-frameworks/rest-fastapi-python:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rest-fastapi-python
spec:
  selector:
    app: rest-fastapi-python
  ports:
    - port: 80
      targetPort: 3000
